export default [
  {"field": "subid", "title": "SubID1", "type": "string", "list": "short"},
  {"field": "subid2", "title": "SubID2", "type": "string", "list": "full"},
  {"field": "subid3", "title": "SubID3", "type": "string", "list": "full"},
  {"field": "subid4", "title": "SubID4", "type": "string", "list": "full"},
  {"field": "subid5", "title": "SubID5", "type": "string", "list": "full"},
  {"field": "state", "title": "State", "type": "string", "list": "full"},
  {"field": "loan_amount", "title": "Loan Amount", "type": "dollar", "list": "full"},
  {"field": "accepted_leads", "title": "Accepted Leads", "type": "int", "list": "short"},
  {"field": "raw_leads", "title": "Raw Leads", "type": "int", "list": "full"},
  {"field": "accepted_pct", "title": "Accepted %", "type": "pct", "list": "full"},
  {"field": "unmatched_leads", "title": "Unmatched", "type": "int", "list": "full"},
  {"field": "unmatched_pct", "title": "Unmatched %", "type": "pct", "list": "full"},
  {"field": "leads_pl", "title": "Flat leads", "type": "int", "list": "short"},
  {"field": "actual_pl", "title": "Flat Revenue", "type": "dollar", "list": "short"},
  {"field": "leads_pf", "title": "Perf. leads", "type": "int", "list": "medium"},
  {"field": "actual_pf", "title": "Perf. Revenue", "type": "dollar", "list": "medium"},
  {"field": "funded", "title": "Funded", "type": "int", "list": "full"},
  {"field": "funded_pct", "title": "Funded %", "type": "pct", "list": "full"},
  {"field": "prd_method1", "title": "Predicted Method1", "type": "float", "list": "medium"},
  {"field": "method1_pct", "title": "Method 1 %", "type": "pct", "list": "full"},
  {"field": "prd_method2", "title": "Predicted Method2", "type": "float", "list": "medium"},
  {"field": "method2_pct", "title": "Method 2 %", "type": "pct", "list": "full"},
  {"field": "adv_expenses", "title": "Adv. Expenses", "type": "dollar", "list": "short"},
  {"field": "avg_lead_cost", "title": "Avg Lead Cost", "type": "dollar", "list": "full"},
  {"field": "avg_loan", "title": "Avg Loan Value", "type": "dollar", "list": "full"},
  {"field": "high_predicted", "title": "High Predicted", "type": "dollar", "list": "medium"},
  {"field": "high_predicted_profit", "title": "High Predicted Profit", "type": "dollar", "list": "medium"},
  {"field": "high_predicted_profit_margin", "title": "High Predicted Profit Margin", "type": "pct", "list": "medium"},
  {"field": "avg_predicted_profit", "title": "Avg. Predicted Profit", "type": "dollar", "list": "medium"},
  {"field": "avg_predicted_profit_margin", "title": "Avg. Margin", "type": "pct", "list": "medium"},
  {"field": "low_predicted", "title": "Low Predicted", "type": "dollar", "list": "medium"},
  {"field": "low_predicted_profit", "title": "Low Predicted Profit", "type": "dollar", "list": "medium"},
  {"field": "low_predicted_profit_margin", "title": "Low Predicted Profit Margin", "type": "pct", "list": "medium"},
  {"field": "call_connections", "title": "Call Connections", "type": "int", "list": "medium"},
  {"field": "connections_pct", "title": "Connection %", "type": "pct", "list": "full"},
  {"field": "credit_pulls", "title": "Credit Pulls", "type": "int", "list": "full"},
  {"field": "credit_pulls_pct", "title": "Credit Pull %", "type": "pct", "list": "full"},
  {"field": "cr_poor", "title": "Poor", "type": "int", "list": "full"},
  {"field": "poor_pct", "title": "Poor %", "type": "pct", "list": "full"},
  {"field": "cr_fair", "title": "Fair", "type": "int", "list": "full"},
  {"field": "fair_pct", "title": "Fair %", "type": "pct", "list": "full"},
  {"field": "cr_good", "title": "Good", "type": "int", "list": "full"},
  {"field": "good_pct", "title": "Good %", "type": "pct", "list": "full"},
  {"field": "cr_excellent", "title": "Excellent", "type": "int", "list": "full"},
  {"field": "excellent_pct", "title": "Excellent %", "type": "pct", "list": "full"},
  {"field": "originations", "title": "Originations", "type": "int", "list": "full"},
  {"field": "originations_pct", "title": "Origination %", "type": "pct", "list": "full"},
  {"field": "applications", "title": "Applications", "type": "int", "list": "full"},
  {"field": "applications_pct", "title": "Applications %", "type": "pct", "list": "full"},
  {"field": "total_profit", "title": "Total Profit", "type": "dollar", "list": "full"},
  {"field": "total_revenue", "title": "Total Revenue", "type": "dollar", "list": "full"},
  {"field": "residuals", "title": "Residuals", "type": "int", "list": "full"},
  {"field": "residual_revenue", "title": "Residual revenue", "type": "dollar", "list": "full"},
  {"field": "company_profit", "title": "Company Profit", "type": "dollar", "list": "full"},
  {"field": "actual_profit_margin_pct", "title": "Actual profit margin %", "type": "pct", "list": "full"},
  {"field": "offer_id", "title": "Offer ID", "type": "int", "list": "full"}
]